using System.Text.Json;
using Xunit;

namespace MapLibreNative.Maui.Torrent.Tests;

/// <summary>
/// Reading the contract the server publishes.
/// </summary>
/// <remarks>
/// The fixtures are generated by pmtiles-swarm's own TileJSON builder, so a
/// change to either side that breaks the contract fails here. Hand-written
/// fixtures would only ever prove this parser agrees with itself.
/// </remarks>
public class TorrentTileJsonTests
{
    private const string InfoHash = "913d671f3a28c5b8d605e28cf6bf01e293d36e86";

    private static TorrentTileJson Load(string name) =>
        TorrentTileJson.Parse(File.ReadAllText(name));

    [Fact]
    public void ReadsTheOrdinaryTileJsonFields()
    {
        TorrentTileJson doc = Load("tilejson-plain.json");

        Assert.Single(doc.Tiles);
        Assert.EndsWith("/{z}/{x}/{y}.pbf", doc.Tiles[0]);
        Assert.Equal(0, doc.MinZoom);
        Assert.Equal(14, doc.MaxZoom);
    }

    [Fact]
    public void ReadsTheTorrentBlock()
    {
        TorrentDescriptor torrent = Load("tilejson-plain.json").Torrent!;

        Assert.Equal(InfoHash, torrent.InfoHash);
        Assert.StartsWith("magnet:?xt=urn:btih:", torrent.Magnet);
        Assert.EndsWith("/archive.torrent", torrent.TorrentUrl);
        Assert.Equal("planet.pmtiles", torrent.Name);
        Assert.Equal(77242531840, torrent.Size);
        Assert.Equal(["https://cdn.example.org/planet.pmtiles"], torrent.WebSeeds);
        Assert.True(torrent.CanJoin);
    }

    [Fact]
    public void ReadsThePublisherKeyOfAMutableArchive()
    {
        TorrentDescriptor torrent = Load("tilejson-mutable.json").Torrent!;

        Assert.NotNull(torrent.Mutable);
        Assert.Equal(new string('a', 64), torrent.Mutable!.PublicKey);
        Assert.Equal("planet", torrent.Mutable.Salt);
        Assert.Equal(7, torrent.Mutable.Sequence);
    }

    [Fact]
    public void ReportsNoMutableIdentityWhenTheArchiveIsFixed()
    {
        Assert.Null(Load("tilejson-plain.json").Torrent!.Mutable);
    }

    [Fact]
    public void AnOrdinaryTileServerParsesFineWithNoTorrent()
    {
        // Not an error: it just cannot be accelerated. Treating this as a
        // failure would make the plugin refuse perfectly good tile servers.
        TorrentTileJson doc = Load("tilejson-ordinary.json");

        Assert.Null(doc.Torrent);
        Assert.Single(doc.Tiles);
        Assert.Equal(14, doc.MaxZoom);
    }

    [Fact]
    public void IgnoresATorrentBlockWithNothingToIdentifyTheArchive()
    {
        // Half a block is worse than none: without an infohash there is no way
        // to know what was joined.
        TorrentTileJson doc = TorrentTileJson.Parse(
            """{"tiles":["https://x/{z}/{x}/{y}.pbf"],"torrent":{"magnet":"magnet:?x"}}""");

        Assert.Null(doc.Torrent);
    }

    [Fact]
    public void ReportsThatItCannotJoinWithoutATorrentOrMagnet()
    {
        TorrentTileJson doc = TorrentTileJson.Parse(
            """{"tiles":[],"torrent":{"infohash":"913d671f3a28c5b8d605e28cf6bf01e293d36e86"}}""");

        Assert.NotNull(doc.Torrent);
        Assert.False(doc.Torrent!.CanJoin);
    }

    [Fact]
    public void ToleratesAMissingWebSeedList()
    {
        TorrentTileJson doc = TorrentTileJson.Parse(
            """{"tiles":[],"torrent":{"infohash":"913d671f3a28c5b8d605e28cf6bf01e293d36e86","magnet":"magnet:?x"}}""");

        Assert.Empty(doc.Torrent!.WebSeeds);
        Assert.True(doc.Torrent.CanJoin);
    }

    [Fact]
    public void ToleratesUnexpectedTypesRatherThanThrowing()
    {
        // A server that publishes something odd should degrade to "no torrent
        // acceleration", not break the map.
        TorrentTileJson doc = TorrentTileJson.Parse(
            """{"tiles":"not-an-array","minzoom":"nope","torrent":42}""");

        Assert.Empty(doc.Tiles);
        Assert.Equal(0, doc.MinZoom);
        Assert.Null(doc.Torrent);
    }

    [Fact]
    public void RejectsSomethingThatIsNotJson()
    {
        // A captive portal or an error page, which is what this looks like in
        // practice. ThrowsAny because the reader throws a JsonException
        // subclass, and the caller only cares that it is one.
        Assert.ThrowsAny<JsonException>(() => TorrentTileJson.Parse("<html>"));
    }
}
